import { NextRequest, NextResponse } from "next/server";
import { writeFileSync, readFileSync, existsSync } from "fs";
import { execSync } from "child_process";
import path from "path";
import { logAudit } from "@/lib/auditLog";

const DB_FILE = path.join(process.cwd(), "data", "services.json");

function extractSubdomain(url: string): string {
  try {
    const host = new URL(url).hostname;
    return host.split(".")[0];
  } catch { return ""; }
}

function generateNginxBlock(svc: { label: string; url: string }, port = 3000): string {
  const sub = extractSubdomain(svc.url);
  if (!sub || !svc.url.includes("digitalrohtak.online")) return "";
  const certPath = "/etc/letsencrypt/live/shopping.digitalrohtak.online";
  return `
# ${svc.label}
server {
    listen 80;
    server_name ${sub}.digitalrohtak.online;
    return 301 https://$host$request_uri;
}
server {
    listen 443 ssl;
    server_name ${sub}.digitalrohtak.online;
    ssl_certificate ${certPath}/fullchain.pem;
    ssl_certificate_key ${certPath}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    location / {
        proxy_pass http://127.0.0.1:${port};
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}`;
}

export async function GET() {
  try {
    if (existsSync(DB_FILE)) {
      const data = JSON.parse(readFileSync(DB_FILE, "utf-8"));
      if (data.services && data.services.length > 0) {
        return NextResponse.json(data);
      }
    }
    return NextResponse.json({ services: [] });
  } catch {
    return NextResponse.json({ services: [] });
  }
}

export async function POST(req: NextRequest) {
  try {
    const { services } = await req.json();

    // 1. Save to JSON
    writeFileSync(DB_FILE, JSON.stringify({ services, updatedAt: new Date().toISOString() }, null, 2));

    // 2. Generate nginx config
    const nginxBlocks = services
      .map((svc: any) => generateNginxBlock(svc))
      .filter(Boolean)
      .join("\n");

    const nginxConf = `# Auto-generated by Digital Rohtak Services Manager\n# Last updated: ${new Date().toISOString()}\n${nginxBlocks}\n`;

    // 3. Write + reload nginx
    writeFileSync("/tmp/digitalrohtak-services.conf", nginxConf);
    execSync(`sudo cp /tmp/digitalrohtak-services.conf /etc/nginx/sites-available/digitalrohtak-services.conf`, { timeout: 5000 });
    execSync(`sudo ln -sf /etc/nginx/sites-available/digitalrohtak-services.conf /etc/nginx/sites-enabled/digitalrohtak-services.conf`, { timeout: 5000 });
    execSync("sudo nginx -t && sudo systemctl reload nginx", { timeout: 10000 });

    // 4. Audit log (fire and forget)
    logAudit(req, "SERVICE_GRID_SAVE", { serviceCount: services?.length || 0 });
    fetch(`http://127.0.0.1:3000/api/ping-google`, { method: "POST" }).catch(() => {});

    return NextResponse.json({ success: true, message: "Saved and nginx reloaded" });
  } catch (err: any) {
    console.error("Services save error:", err.message);
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
