import { model } from "@medusajs/framework/utils"

export const ServiceProvider = model.define("service_provider", {
  id: model.id().primaryKey(),
  category_id: model.text().nullable(),
  full_name: model.text(),
  mobile: model.text(),
  email: model.text().nullable(),
  gender: model.text().nullable(),
  date_of_birth: model.dateTime().nullable(),
  profile_photo: model.text().nullable(),
  short_bio: model.text().nullable(),
  locality: model.text().nullable(),
  address: model.text().nullable(),
  pincode: model.text().nullable(),
  city: model.text().default("Rohtak"),
  state: model.text().default("Haryana"),
  lat: model.number().nullable(),
  lng: model.number().nullable(),
  service_radius_km: model.number().default(5),
  experience_years: model.number().nullable(),
  languages_spoken: model.text().nullable(),
  service_location: model.text().default("Both"),
  home_visit_charges: model.number().default(0),
  working_days: model.text().nullable(),
  working_hours_start: model.text().nullable(),
  working_hours_end: model.text().nullable(),
  slot_duration_minutes: model.number().default(60),
  advance_booking_days: model.number().default(7),
  cancellation_window_hours: model.number().default(2),
  deposit_required: model.boolean().default(false),
  deposit_percent: model.number().default(0),
  accepts_cash: model.boolean().default(true),
  accepts_upi: model.boolean().default(true),
  accepts_card: model.boolean().default(false),
  whatsapp_number: model.text().nullable(),
  social_instagram: model.text().nullable(),
  social_facebook: model.text().nullable(),
  intro_video: model.text().nullable(),
  is_verified: model.boolean().default(false),
  verified_at: model.dateTime().nullable(),
  is_active: model.boolean().default(false),
  rating_avg: model.number().default(0),
  rating_count: model.number().default(0),
  total_bookings: model.number().default(0),
})
